/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author diosl
 */
public class Ventana1 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana1
     */
    Colores colores = new Colores();

    public Ventana1() {
        initComponents();
        this.setSize(800, 550);
        this.setResizable(false);
        this.setTitle("Connection SQL Server");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        texNotf = new javax.swing.JLabel();
        btnConectar = new javax.swing.JButton();
        btnDesconectar = new javax.swing.JButton();
        etq = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(colores.getFondo1());
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(colores.getFondo1());
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 480));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel3.setBackground(colores.getFondo1());
        jPanel3.setPreferredSize(new java.awt.Dimension(800, 480));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texNotf.setBackground(new java.awt.Color(255, 255, 255));
        texNotf.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        texNotf.setForeground(new java.awt.Color(204, 204, 204));
        texNotf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texNotf.setPreferredSize(new java.awt.Dimension(800, 20));
        jPanel3.add(texNotf, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 800, -1));

        btnConectar.setBackground(colores.getColorPrymary());
        btnConectar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnConectar.setForeground(new java.awt.Color(255, 255, 255));
        btnConectar.setText("Conectar");
        jPanel3.add(btnConectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 150, -1));

        btnDesconectar.setBackground(colores.getColorPrymary());
        btnDesconectar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnDesconectar.setForeground(new java.awt.Color(255, 255, 255));
        btnDesconectar.setText("Desconectar");
        jPanel3.add(btnDesconectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 150, -1));

        etq.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        etq.setForeground(colores.getColorPrymary());
        etq.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/data-regular-36 (1).png"))); // NOI18N
        etq.setText("Connection SQL Server");
        etq.setEnabled(false);
        jPanel3.add(etq, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 800, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 220;
        gridBagConstraints.ipady = 190;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jPanel3, gridBagConstraints);

        jPanel4.add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setBackground(colores.getFondo1());
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 20));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("2020 BrunoDev, All Copyright ©");
        jLabel1.setPreferredSize(new java.awt.Dimension(800, 20));
        jPanel2.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel2, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnConectar() {
        return btnConectar;
    }

    public JButton getBtnDesconectar() {
        return btnDesconectar;
    }

    public JLabel getEtq() {
        return etq;
    }

    public JLabel getTexNotf() {
        return texNotf;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConectar;
    private javax.swing.JButton btnDesconectar;
    private javax.swing.JLabel etq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel texNotf;
    // End of variables declaration//GEN-END:variables
}
